import Head from "next/head";
import { Container } from "react-bootstrap";
import Aos from "aos";
import React from "react";
import "aos/dist/aos.css";

const Contact = () => {
  React.useEffect(() => {
    Aos.init({ duration: 750 });
  }, []);
  return (
    <>
      <Head>
        <title>Contact us - Stack citi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-aos="fade-up">
        <Container>
          <h3>contact</h3>
        </Container>
      </div>
    </>
  );
};

export default Contact;
