import Head from "next/head";
import { Container } from "react-bootstrap";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact us - Stack citi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h3>contact</h3>
      </Container>
    </>
  );
};

export default Contact;
