import Head from "next/head";
import Hero from "../components/hero";
import HeroTwo from "../components/herotwo";
import Process from "../components/process";
import Works from "../components/work";
import Testimonials from "../components/testimonials";
import Contact from "../components/contact";

const Home = () => {
  return (
    <>
      <Head>
        <title>Stack citi - Design website agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <HeroTwo />
        <Process />
        <Works />
        <Testimonials />
        <Contact />
      </div>
    </>
  );
};

export default Home;
