import Head from "next/head";
import { Container } from "react-bootstrap";
import Aos from "aos";
import React from "react";
import "aos/dist/aos.css";

const Pricing = () => {
  return (
    <>
      <Head>
        <title>Our pricing - Stack citi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-aos="fade-up">
        <h3> pricing</h3>
      </div>
    </>
  );
};

export default Pricing;
