import Head from "next/head";

const pricing = () => {
  return (
    <>
      <Head>
        <title>Our pricing - Stack citi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3> pricing</h3>
    </>
  );
};

export default pricing;
